name: KamsTweaks
version: '1.2.3'
main: kam.kamsTweaks.KamsTweaks
api-version: '1.21'

# i was lied to about plugin's permissions.yml
permissions:
  kamstweaks.landclaims.manageall:
    default: op
    description: "Manage any player's land claims"
  kamstweaks.landclaims.claim:
    default: true
    description: "Claim land or entities"

  kamstweaks.hat:
    default: true
    description: "Use /hat"

  kamstweaks.names.nick:
    default: true
    description: "Set own nickname"
  kamstweaks.names.color:
    default: true
    description: "Set own name color"

  kamstweaks.teleports.back:
    default: true
    description: "Teleport back to previous location"
  kamstweaks.teleports.homes:
    default: true
    description: "Set or teleport to homes"
  kamstweaks.teleports.tpa:
    default: true
    description: "Request to teleport to someone"
  kamstweaks.teleports.warp:
    default: true
    description: "Teleport to a warp"
  kamstweaks.teleports.warps:
    default: true
    description: "List all warps"
  kamstweaks.teleports.addwarp:
    default: op
    description: "Create a new warp"
  kamstweaks.teleports.spawn:
    default: true
    description: "Teleport to spawn"

  kamstweaks.silkspawner:
    default: true
    description: "Use silk touch on spawners"

  kamstweaks.configure:
    default: op
    description: "Change settings for KamsTweaks"