name: KamsTweaks
version: '${version}'
main: kam.kamsTweaks.KamsTweaks
api-version: '26.2'
bootstrapper: kam.kamsTweaks.Bootstrapper

dependencies:
  server:
    DiscordSRV:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: BEFORE
      required: false